FROM ubuntu:18.04
RUN apt-get -y update \
&& apt-get -y install gnuplot

ENV WD /working_dir
WORKDIR ${WD}
ENV ROSETTA3_DB /database

ADD wrapper.sh ${WD}
ADD r_frag_quality.static.linuxgccrelease ${WD} 

ENV PATH="/database:/working_dir:${PATH}"
ENTRYPOINT ["/working_dir/wrapper.sh", "-database /de-app-work/database", "-in:file:native outfile.pdb", "-f outfile.200.3mers"]
