FROM ubuntu:18.04
RUN apt-get -y update

ENV WD /working_dir
WORKDIR ${WD}
ENV ROSETTA3_DB ${WD}/database

ADD wrapper.sh ${WD}
ADD fragment_picker.static.linuxgccrelease ${WD} 
COPY filtered.vall.dat.2006-05-05.gz ${WD}/filtered.vall.dat.2006-05-05.gz

ENTRYPOINT ["/working_dir/wrapper.sh", "-database /working_dir/database", "-vall /working_dir/filtered.vall.dat.2006-05-05.gz"]
