FROM ubuntu:16.04
RUN apt-get -y update

LABEL maintainer = "Florian Wieser"

WORKDIR /working_dir
RUN mkdir -p /working_dir/output_files
ADD  AbinitioRelax.static.linuxgccrelease AbinitioRelax.static.linuxgccrelease

COPY input_files input_files
COPY database database

ENV ROSETTA3_DB=/working_dir/database

ENTRYPOINT ["/working_dir/AbinitioRelax.static.linuxgccrelease"]
CMD ["@/working_dir/input_files/options"]
